project:
  type: book
  output-dir: BOOK
  resources:
    - data

author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722

citation:
  type: book
  title: "table traineR"
  publisher: "Hochschule Niederrhein"
  publisher-place: "Krefeld"
  language: de
  status: "advance online publication"
  license: "CC BY-NC-SA 4.0"
  url: https://github.com/produnis/tabletrainer
  public-url: https://www.produnis.de/tabletrainer
  fulltext-url: https://www.produnis.de/tabletrainer
  pdf-url: https://www.produnis.de/tabletrainer/tabletraineR.pdf

book:
  title: "table traineR"
  subtitle: "Workouts für {data.table}"
  language: de
  author:
    - name: Prof. Dr. Jörg große Schlarmann
      url: https://www.produnis.de/R
      affiliation: Hochschule Niederrhein
      affiliation-url: https://www.hs-niederrhein.de
      orcid: 0000-0002-3634-7722
  date: "2024-11-03"
  date-format: "DD.MM.YYYY"
  cover-image: images/Titelbild.jpg
  favicon: images/favicon.ico
  output-file: tabletraineR
  description:  |
    In diesem Buch sind zahlreiche Übungen zur freien Statistiksoftware R enthalten, die sich ausschließlich mit dem Paket {data.table} befassen.
  sidebar:
    collapse-level: 4
  downloads:
    - pdf
    - epub
  open-graph:
    image: "https://www.produnis.de/tabletrainer/images/Titelbild.jpg"
    locale: de_DE
  twitter-card:
    image: "https://www.produnis.de/tabletrainer/images/Titelbild.jpg"
    creator: "produnis"
  chapters:
    - index.qmd
    - einleitung.qmd
    - datatable.qmd
    - aufgaben.qmd
    - loesungen.qmd
    - literatur.qmd
    - credits.qmd
  page-footer:
    right:
      - icon: github
        href: https://github.com/produnis/tabletrainer
      - icon: linkedin
        href: https://www.linkedin.com/in/j%C3%B6rg-gro%C3%9Fe-schlarmann-32b3331b7/
      - icon: mastodon
        href: https://mastodon.social/@rbuch
      - icon: file-earmark-pdf
        href: tabletraineR.pdf
      - icon: journal-richtext
        href: tabletraineR.epub

number-sections: true
bibliography: literatur.bib
csl: apa-single-spaced.csl
nocite: |
  @waltherR22, @tidytuesday, @Rbase, @wickham23
lang: de

language:
  crossref-sec-prefix: "Abschnitt"
  crossref-chap-prefix: "Abschnitt"
freeze: auto

format:
    buechlein-html: default
    buechlein-epub: default
    buechlein-pdf: default
